### ISSUE TITLE
Problem with firebase in build

### ISSUE THREAD

**Issue by Warmachine13** [ashrithks/rn-text-detector#1]
Error before open app on android

 E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.leituradata, PID: 14144
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/ml/vision/FirebaseVision;
        at com.fetchsky.RNTextDetector.RNTextDetectorModule.<init>(RNTextDetectorModule.java:37)
        at com.fetchsky.RNTextDetector.RNTextDetectorPackage.createNativeModules(RNTextDetectorPackage.java:17)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.ml.vision.FirebaseVision" on path: DexPathList[[zip file "/data/app/com.leituradata-J3FXScp1al6PD3sFfDhpwQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.leituradata-J3FXScp1al6PD3sFfDhpwQ==/lib/x86, /data/app/com.leituradata-J3FXScp1al6PD3sFfDhpwQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.fetchsky.RNTextDetector.RNTextDetectorModule.<init>(RNTextDetectorModule.java:37) 
        at com.fetchsky.RNTextDetector.RNTextDetectorPackage.createNativeModules(RNTextDetectorPackage.java:17) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by ashrithks** [comment]
Updated the package which uses on device MLkit
